VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Configure the machine build
    config.vm.box = "ubuntu/trusty64"

    # Configure the machine hostname
    config.vm.hostname = "ubuntu"

    # Configure A Private Network IP
    config.vm.network :private_network, ip: "192.168.22.20"

    # Configure some custom machine configurations
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    # Configure Port Forwarding
    config.vm.network "forwarded_port", guest: 80, host: 8000
    config.vm.network "forwarded_port", guest: 3306, host: 33060
    config.vm.network "forwarded_port", guest: 5432, host: 54320
    config.vm.network "forwarded_port", guest: 35729, host: 35730

    # Configure Port Forwarding for Elasticsearch
    config.vm.network "forwarded_port", guest:9200, host: 62000

    # Register All Of The Configured Shared Folders
    config.vm.synced_folder "~/CodeLab/pioneer/sync", "/home/vagrant/sync"

    # Install Ansible
    config.vm.provision "shell", path: "~/CodeLab/pioneer/vagrant/ansible.sh"

    # Install Personal bash_aliases
    config.vm.provision "shell", path: "~/CodeLab/pioneer/vagrant/bash_aliases.sh"
end
